# Generated by Django 3.2.9 on 2021-12-15 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='print_image',
            new_name='gallery_image',
        ),
    ]
