# Generated by Django 3.2.9 on 2021-12-12 10:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prints', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Print',
        ),
        migrations.RenameField(
            model_name='print',
            old_name='post_image',
            new_name='print_image',
        ),
    ]
