# Generated by Django 4.0 on 2021-12-11 14:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 11, 14, 1, 18, 969272, tzinfo=utc)),
        ),
    ]
