# Generated by Django 3.2.9 on 2021-12-12 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
